const bgColors = [
			'#A8B820','#705848','#7038F8','#F8D030','#EE99AC','#C03028',
			'#F08030','#A890F0','#705898','#78C850','#E0C068','#98D8D8',
			'#A8A878','#A040A0','#F85888','#B8A038','#B8B8D0','#6890F0'
            ];
const pkm = [
    [
      'caterpie',null,null,'joltik','cutiefly',
      'heracross','larvesta','butterfree','shedinja','paras',
      'nincada',null,null,'weedle','dottler',
      'shuckle','forretress','surskit'
    ],
    [
      null,'umbreon','deino',null,'impidimp',
      'scraggy','houndour','murkrow','sableye','zarude',
      null,'sneasel','obstagoon',null,'inkay',
      null,'pawniard',null
    ],
    [
      null,null,'dratini','zekrom','altaria-mega',
      'hakamo-o','reshiram','dragonite','dreepy',null,
      'gible','kyurem',null,null,'latias',
      null,null,null
    ],
    [
      null,'morpeko','dracozolt','pikachu','dedenne',
      null,'rotom-heat','zapdos','rotom','rotom-mow',
      null,'rotom-frost','helioptile','toxel','raichu-alola',
      null,'magnemite','rotom-wash'
    ],
    [
      null,null,null,null,'clefairy',
      null,null,'togetic',null,null,
      null,null,null,null,null,
      null,'zacian-crowned',null
    ],
    [
      null,'pangoro',null,null,null,
      'mankey',null,'hawlucha','marshadow',null,
      null,'crabominable',null,null,'meditite',
      null,'lucario','urshifu'
    ],
    [
      'sizzlipede','incineroar','turtonator',null,null,
      'combusken','charmander','moltres','blacephalon',null,
      'numel',null,'litleo',null,'delphox',
      'magcargo','heatran','volcanion'
    ],
    [
      null,null,'noibat',null,null,
      null,null,'rookidee',null,null,
      null,null,null,null,null,
      null,'corviknight','cramorant'
    ],
    [
      null,'spiritomb','giratina',null,'mimikyu',
      null,'litwick','drifloon','misdreavus','phantump',
      'sandygast',null,null,'gastly',null,
      null,null,null
    ],
    [
      null,'nuzleaf','applin',null,'cottonee',
      'breloom',null,'hoppip','decidueye','tangela',
      'torterra','snover',null,'bulbasaur','exeggcute',
      null,'ferroseed',null
    ],
    [
      null,'sandile','vibrava','stunfisk',null,
      null,'groudon-primal','gligar','golett',null,
      'sandshrew',null,null,null,'baltoy',
      null,'excadrill',null
    ],
    [
      'snom',null,null,null,'ninetales-alola',
      null,'darmanitan-galar-zen','articuno','froslass',null,
      'swinub','snorunt',null,null,'jynx',
      null,'sandshrew-alola','spheal'
    ],
    [
      null,null,'drampa',null,'jigglypuff',
      'audino-alola',null,'pidgey',null,'deerling',
      'diggersby',null,'rattata',null,'girafarig',
      null,null,'bibarel'
    ],
    [
      'skorupi','stunky','dragalge',null,'weezing-galar',
      'croagunk','salandit','zubat',null,null,
      'nidoqueen',null,null,'ekans','slowbro-galar',
      null,null,'skrelp'
    ],
    [
      null,'hoopa-unbound',null,null,'mr-mime',
      'gallade','victini','natu','lunala','celebi',
      null,'calyrex-ice-rider','indeedee',null,'abra',
      null,'solgaleo',null
    ],
    [
      'anorith','tyranitar','tyrunt','geodude-alola','carbink',
      'terrakion','carkol','aerodactyl',null,'lileep',
      'geodude','amaura',null,'nihilego','lunatone',
      'sudowoodo','shieldon','omanyte'
    ],
    [
      null,null,'dialga',null,'mawile',
      'cobalion',null,,'skarmory','honedge',null,
      'steelix',null,null,null,'beldum',
      'aron','registeel',null
    ],
    [
      'dewpider','carvanha','Kingdra','chinchou','marill',
      'poliwrath',null,'gyarados','frillish','lotad',
      'wooper','dewgong',null,'tentacool','slowpoke',
      'corsola','empoleon','squirtle'
    ]
];